import { ReversiState } from "./Reversi.ts";

export interface ReversiItem {
  code: ReversiItemCode;
  icon: string;
  name: string;
  desc: string;
  price: number;
  isUnique: boolean;
  currentValue?: number;
  amount?: number;
  value?: number;
  used?: boolean;
  usedFor?: ReversiState;
}

export const ReversiItemCode = {
  Yokoplus: "YOKO_PLUS",
  Tateplus: "TATE_PLUS",
  Nanameplus: "NANAME_PLUS",
  Bank: "BANK",
  Moai: "MOAI",
  Mail: "MAIL",
  Email: "EMAIL",
  Ring: "RING",
  Jewel: "JEWEL",
  Cart: "CART",
  Orange: "ORANGE",
  Pass: "PASS",
  EightBall: "EIGHT_BALL",
  WhiteMonolis: "WHITE_MONOLIS",
  BlackMonolis: "BLACK_MONOLIS",
  Abacus: "ABACUS",
  Study: "STUDY",
  Reload: "RELOAD",
  Interest: "INTEREST",
  Insurance: "INSURANCE",
  JudgeMoon: "JUDGE_MOON",
  Rat: "RAT",
  Dmz: "DMZ",
  Aquarias: "AQUARIAS",
} as const;
export type ReversiItemCode =
  (typeof ReversiItemCode)[keyof typeof ReversiItemCode];

export const ReversiInitialUnlocked = [
  ReversiItemCode.Yokoplus,
  ReversiItemCode.Tateplus,
  ReversiItemCode.Bank,
  ReversiItemCode.Moai,
  ReversiItemCode.Mail,
  ReversiItemCode.Ring,
  ReversiItemCode.Cart,
  ReversiItemCode.Pass,
  ReversiItemCode.EightBall,
  ReversiItemCode.WhiteMonolis,
  ReversiItemCode.BlackMonolis,
  ReversiItemCode.Abacus,
  ReversiItemCode.Study,
  ReversiItemCode.Interest,
  ReversiItemCode.Insurance,
  ReversiItemCode.JudgeMoon,
  ReversiItemCode.Rat,
] as const;

export const ReversiItems: ReversiItem[] = [
  {
    code: ReversiItemCode.Yokoplus,
    icon: "↔️",
    name: "ヨコプラス",
    desc: "ラウンド開始時、盤の横幅を$v増やす。横幅の最大は12",
    price: 15,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Tateplus,
    icon: "↕️",
    name: "タテプラス",
    desc: "ラウンド開始時、盤の縦幅を$v増やす。縦幅の最大は12",
    price: 15,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Nanameplus,
    icon: "↘️",
    name: "ナナメプラス",
    desc: "ラウンド開始時、盤の幅を$vずつ増やす。幅の最大は12",
    price: 15,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Bank,
    icon: "🏦",
    name: "法定利率",
    desc: "ラウンド終了時、所持🪙の$v%を獲得する",
    price: 6,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Moai,
    icon: "🗿",
    name: "モアイ",
    desc: "⚫の配置時、$v%で🗿に変換。🗿は反転されない",
    price: 4,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Mail,
    icon: "✉️",
    name: "宛先不明郵便",
    desc: "⚪の配置時、$v%で✉️に変換。✉️は💠3🪙1",
    price: 4,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Email,
    icon: "📧",
    name: "SSTプロトコル",
    desc: "⚪の配置時、$v%で📧に変換。📧は💠5🪙1",
    price: 6,
    isUnique: false,
    value: 20,
  },
  {
    code: ReversiItemCode.Ring,
    icon: "💍",
    name: "永遠の愛",
    desc: "⚪の配置時、$v%で💍に変換。💍は💠1🪙3",
    price: 4,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Jewel,
    icon: "💎",
    name: "永遠の煌き",
    desc: "⚪の配置時、$v%で💎に変換。💎は💠1🪙5",
    price: 6,
    isUnique: false,
    value: 20,
  },
  {
    code: ReversiItemCode.Cart,
    icon: "🛒",
    name: "買い物カート",
    desc: "アイテムの枠を$v個増やす。",
    price: 3,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Orange,
    icon: "🍊",
    name: "オラニエ公の愛",
    desc: "ラウンド開始時、$v%で🍊を配置。🍊は中立で💠5🪙5",
    price: 8,
    isUnique: false,
    value: 10,
  },
  {
    code: ReversiItemCode.Pass,
    icon: "🫲",
    name: "ドローゴー",
    desc: "$v回使用可。黒番をパスできる",
    price: 3,
    isUnique: true,
    value: 3,
    used: false,
    usedFor: "IN_ROUND",
  },
  {
    code: ReversiItemCode.EightBall,
    icon: "🎱",
    name: "エイトボール",
    desc: "$v回使用可。次の黒番で🎱を配置。🎱は反転されない",
    price: 5,
    isUnique: true,
    value: 3,
    used: false,
    usedFor: "IN_ROUND",
  },
  {
    code: ReversiItemCode.BlackMonolis,
    icon: "⬛",
    name: "黒のモノリス",
    desc: "⚫の配置時の変換効果が、黒による反転時にも発生する",
    price: 15,
    isUnique: true,
  },
  {
    code: ReversiItemCode.WhiteMonolis,
    icon: "⬜",
    name: "白のモノリス",
    desc: "⚪️の配置時の変換効果が、白による反転時にも発生する",
    price: 15,
    isUnique: true,
  },
  {
    code: ReversiItemCode.Abacus,
    icon: "🧮",
    name: "不正会計",
    desc: "反転した石の総💠が10以上の場合、それを2倍",
    price: 12,
    isUnique: true,
  },
  {
    code: ReversiItemCode.Study,
    icon: "📚",
    name: "未来への投資",
    desc: "反転した石の総🪙を半分💠に変換する",
    price: 12,
    isUnique: true,
  },
  {
    code: ReversiItemCode.Reload,
    icon: "🔄",
    name: "購買再起素子",
    desc: "$v回使用可。無料でリロールする",
    price: 6,
    isUnique: true,
    value: 1,
    used: false,
    usedFor: "INTERVAL",
  },
  {
    code: ReversiItemCode.Interest,
    icon: "💹",
    name: "逆進性の税",
    desc: "反転した石の総💠を(現在🪙×$v)%増やす",
    price: 9,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Insurance,
    icon: "🪪",
    name: "社会保障番号",
    desc: "⚫の配置時、🪙$vを得る",
    price: 8,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.JudgeMoon,
    icon: "🌓",
    name: "ジャッジ・ムーン",
    desc: "ラウンド終了前、💠(黒石の数x$v)を得る",
    price: 8,
    isUnique: false,
    value: 1,
  },
  {
    code: ReversiItemCode.Rat,
    icon: "🐀",
    name: "群れネズミ",
    desc: "⚫の配置時、$v%で🐀に変換。🐀は白番後に💠1生産",
    price: 4,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Dmz,
    icon: "🌻",
    name: "DMZ",
    desc: "⚫の配置時、$v%で🌻に変換。🌻は中立で白番後に💠2生産",
    price: 6,
    isUnique: false,
    value: 30,
  },
  {
    code: ReversiItemCode.Aquarias,
    icon: "♒",
    name: "水瓶座の徽章",
    desc: "白番の後に追加の白番が増える。反転した石の総💠が2倍",
    price: 5,
    isUnique: true,
  },
] as const;
